language: python
python:
  - 2.7
  - 3.3

install:
  - python setup.py install
  - cd tests/plugin1 && python setup.py install
  - pip install cov-core coverage coveralls nose-cov

script: coverage run setup.py -q nosetests

after_success: coveralls
